// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	admin "luckygo/app/gateway/internal/handler/admin"
	auth "luckygo/app/gateway/internal/handler/auth"
	pub "luckygo/app/gateway/internal/handler/pub"
	user "luckygo/app/gateway/internal/handler/user"
	"luckygo/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/activities",
				Handler: admin.CreateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities",
				Handler: admin.ListActivitiesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/:id",
				Handler: admin.GetActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/activities/:id",
				Handler: admin.UpdateActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/activities/:id/ui-config",
				Handler: admin.UpdateUiConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/cancel",
				Handler: admin.CancelActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/draw",
				Handler: admin.ForceDrawHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/pause",
				Handler: admin.PauseActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/publish",
				Handler: admin.PublishActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/resume",
				Handler: admin.ResumeActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/:id/winners",
				Handler: admin.ActivityWinnersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/activities/:id/participants",
				Handler: admin.ListParticipantsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/participants/import",
				Handler: admin.ImportParticipantsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/activities/:id/participants/:pid",
				Handler: admin.DeleteParticipantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/live-draw",
				Handler: admin.LiveDrawHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/live-draw/undo",
				Handler: admin.LiveDrawUndoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/activities/:id/offline-redeem",
				Handler: admin.OfflineRedeemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/blacklist",
				Handler: admin.BlacklistAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/redeem",
				Handler: admin.RedeemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: admin.UploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register-tenant",
				Handler: auth.RegisterTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register-user",
				Handler: auth.RegisterUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/play/:publicId",
				Handler: pub.GetPublicActivityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/play/:publicId/feed",
				Handler: pub.PublicFeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/play/:publicId/winners",
				Handler: pub.PublicWinnersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/enroll",
				Handler: user.EnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/me/address",
				Handler: user.FillAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/prizes",
				Handler: user.MyPrizesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	// 上传文件公开读取（图片：奖品图/头像/背景图）
	server.AddRoute(rest.Route{
		Method:  http.MethodGet,
		Path:    "/api/static/uploads/:filename",
		Handler: admin.StaticUploadHandler(serverCtx),
	})
}
